### ISSUE TITLE
Query to assess usage of web fonts

### ISSUE THREAD

**Issue by felixarntz** [GoogleChromeLabs/wpp-research#11]
* Create HTTP Archive query to get **% of WordPress sites that use _any_ web fonts**
* Create HTTP Archive query to get **distribution of number of web fonts used per site** only for WordPress sites that use at least 1 web font
* Create HTTP Archive query to get **% of WordPress sites that use `swap` vs `fallback` font-display strategy for any web fonts**

**Comment by felixarntz** [comment]
cc @ankitrox

**Comment by vishalkakadiya** [comment]
@kt-12 @felixarntz I tried to dig into the HTTP archive database and other places, but I'm not able to create any good query yet. I would appreciate your help in building it. We might refer almanac query for the `font display usage, which is below:
> https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/fonts/font_display_usage.sql

**Comment by vishalkakadiya** [comment]
I have found another good reference, I will create some queries now based on it. Thank you!
> https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/fonts/popular_font_families_by_vendor.sql

CC @felixarntz @kt-12

**Comment by vishalkakadiya** [comment]
@kt-12 I have tried to create a query for the first point here. Can you review this once? Thank you!

```
SELECT
  client,
  JSON_EXTRACT_SCALAR(payload, '$._font_details.OS2.achVendID') AS vendor,
  JSON_EXTRACT_SCALAR(payload, '$._font_details.names[1]') AS family,
  COUNT(0) AS total,
  COUNT(0) * 1.0 / SUM(COUNT(0)) OVER(PARTITION BY client) AS pct
FROM
  `httparchive.almanac.requests` AS requests
  JOIN 
  `httparchive.technologies.2022_10_01_*` AS tech 
ON 
  tech.url = requests.url 
WHERE 
  requests.client = tech._TABLE_SUFFIX 
AND 
  tech.app = 'WordPress'
AND
  requests.type = 'font'
GROUP BY
  client,
  vendor,
  family
QUALIFY
  pct > 0.001
ORDER BY pct DESC
```

**Comment by vishalkakadiya** [comment]
@kt-12 Here is the query for the 3rd point based on [this reference](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/fonts/font_display_usage.sql).

> Create HTTP Archive query to get % of WordPress sites that use swap vs fallback font-display strategy for any web fonts

```
CREATE TEMPORARY FUNCTION getFontDisplay(json STRING)
RETURNS ARRAY < STRING >
LANGUAGE js
OPTIONS(library = "gs://httparchive/lib/css-utils.js")
AS '''
try {
  const ast = JSON.parse(json);
  const result = [];
  walkDeclarations(ast, decl => {
    result.push(decl.value);
  }, {
    properties: 'font-display',
    rules: r => r.type === 'font-face'
  });
  return result;
} catch (e) {
  return [];
}
''';

SELECT
  client,
  font_display,
  pages,
  total,
  pages / total AS pct
FROM (
  SELECT
    client,
    font_display,
    COUNT(DISTINCT page) AS pages
  FROM
    `httparchive.almanac.parsed_css`,
    UNNEST(getFontDisplay(css)) AS font_display
  WHERE
    date = '2022-11-01'
  GROUP BY
    client,
    font_display)
JOIN (
  SELECT
    pages._TABLE_SUFFIX AS client,
    COUNT(0) AS total
  FROM
    `httparchive.summary_pages.2022_11_01_*` as pages
  JOIN 
  `httparchive.technologies.2022_11_01_*` AS tech 
ON 
  tech.url = pages.url 
WHERE 
  pages._TABLE_SUFFIX = tech._TABLE_SUFFIX 
AND 
  tech.app = 'WordPress'
  GROUP BY
    client)
USING
  (client)
ORDER BY
  pct DESC
 ```

**Comment by kt-12** [comment]
Ref: https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/fonts/font_usage_over_time.sql
@vishalkakadiya  I got an even smaller summary table from the reference above, that directly covered most of what we wanted for queries 1 and 2. I have added both queries to the draft PR #34 along with their results.

**Comment by vishalkakadiya** [comment]
@kt-12 Your PR looks good to me. Thank you!
