### ISSUE TITLE
Query to assess impact of inaccurate `sizes` attribute per `<img>`

### ISSUE THREAD

**Issue by felixarntz** [GoogleChromeLabs/wpp-research#12]
* Create HTTP Archive query similar to https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/media/image_srcset_sizes_per_image_accuracy_impact.sql, only that it should be scoped to cover exclusively WordPress sites

**Comment by felixarntz** [comment]
cc @ankitrox @vishalkakadiya

**Comment by vishalkakadiya** [comment]
@felixarntz I have added a PR for this. Can you review it in your free time? Thank you! 
> https://github.com/GoogleChromeLabs/wpp-research/pull/19
