### ISSUE TITLE
The benchmark-web-vitals CLI script blocked by CSPs

### ISSUE THREAD

**Issue by joemcgill** [GoogleChromeLabs/wpp-research#65]
The `benchmark-web-vitals` CLI script included in this repo attempts to [load the web-vitals library from a CDN](https://github.com/GoogleChrome/web-vitals#load-web-vitals-from-a-cdn) ([code reference](https://github.com/GoogleChromeLabs/wpp-research/blob/a58609b76f773f0ee60af32942b4f910ce45ab69/cli/commands/benchmark-web-vitals.mjs#L204-L206)) in order to collect web vitals metrics.

However, if a site has a CSP that does not allow loading scripts from an external source, the script will fail silently and only capture the Success Rate metric.

## Reproduction Steps

1. Edit the line in `benchmark-web-vitals.mjs` that launches puppeteer so it will open a non-headless version:

```js
const browser = await puppeteer.launch({ headless:false });
```

2. Try to do a benchmark of a site with a restrictive CSP, e.g.:

```
npm run research -- benchmark-web-vitals --url https://10up.com -n 1
```

3. Open the browser console of the page that is opened by puppeteer and see that the script has been blocked.

**Comment by swissspidy** [comment]
Instead of relying on unpkg.com we could install the package locally use `page.addScriptTag({ path: 'path/to/web-vitals.js' })` to inject the web-vitals library into the browser page

**Comment by westonruter** [comment]
_However_ if a site doesn't implement Strict CSP with nonces, and they instead opt for [hashes](https://content-security-policy.com/hash/), then we'd also need to compute the hash and inject it into the CSP header somehow.

**Comment by swissspidy** [comment]
Good point. Though both nonces and hashes seem like quite the edge cases for a script like this, so not sure we wanna spend time looking into that.

**Comment by westonruter** [comment]
I mean a site may implement CSP with either nonces or hashes. So if we want to be able to run this on any site, we should implement both.

**Comment by swissspidy** [comment]
Yes I got that part, I phrased it poorly. Just seems like a low prio. I'd say let's cross that bridge (nonces and hashes) when we get there.

**Comment by westonruter** [comment]
Oh, turns out there's a way to disable CSP entirely in Puppeteer! 

All we need to do is use [`setBypassCSP`](https://pptr.dev/api/puppeteer.page.setbypasscsp):

```js
await page.setBypassCSP( true );
```
